name: Build & publish viamrtsp module for Android

# on:
#   release:
#     types: [published]

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - run_command: "TARGET_OS=android TARGET_ARCH=arm64 make module"
            platform: android/arm64
          - run_command: "make module"
            platform: linux/arm64
          - run_command: "make module"
            platform: linux/amd64

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build viamrtsp binary and package module
      run: ${{ matrix.run_command }}
    
    - name: Upload viamrtsp module to registry
      uses: viamrobotics/upload-module@main
      with:
        meta-path: meta.json
        module-path: module.tar.gz
        platform: ${{ matrix.platform }}
        version: 0.0.2
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
